steam/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
from django.core.urlresolvers import reverse_lazy


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^steamapp/', include('steamapp.urls', namespace='steamapp')),
    url(r'^api/auth/', include('rest_framework.urls', namespace='rest_framework')),
]

steamapp/urls.py
from django.conf.urls import url
from django.conf import settings
from django.contrib.auth.views import login, logout
from rest_framework.urlpatterns import format_suffix_patterns
from django.core.urlresolvers import reverse_lazy

from models import Player, Game, Achievement, OwnedGame, OwnedAchievement, GameReview

from forms import PlayerForm, GameForm, AchievementForm, OwnedGameForm, OwnedAchievementForm, GameReviewForm

from views import PlayerList, PlayerDetail, GameList, GameDetail, \
                  OwnedGameDetail, AchievementList, \
                  AchievementDetail, OwnedAchievementDetail, HomeView

from views import PlayerCreate, GameCreate, OwnedGamePlayerCreate, OwnedGameGameCreate, \
                  AchievementCreate, OwnAchPlayerCreate, OwnAchAchCreate, AchievementGameCreate, \
                  GameReviewCreate

from views import LoginRequiredCheckIsOwnerUpdateView, LoginRequiredCheckIsOwnerDeleteView

from views import APIPlayerList,APIPlayerDetail,APIGameList,APIGameDetail, \
                  APIAchievementList,APIAchievementDetail,APIOwnedGameDetail,\
                  APIOwnedAchievementDetail

urlpatterns = [
    # Home page
    url(r'^$',
        HomeView.as_view(template_name='steamapp/home.html'),
        name = 'home'),

    #Login
     url(r'^login/$',
        login,
        name='login'),

    #Logout
    url(r'^logout/$',
        logout,
        name='logout',
        kwargs={'next_page': '/'}),

    # List Players: /steamapp/player.json
    url(r'^players(\.(?P<extension>(json|xml)))?$',
        PlayerList.as_view(),
        name='player_list'),

    # Player details, /steamapps/players/<steamid>.json
    url(r'^players/(?P<pk>\d+)(\.(?P<extension>(json|xml)))?$',
        PlayerDetail.as_view(),
        name='player_detail'),

    # Create a Player: /steamapp/players/create/
    url(r'^players/create/$',
        PlayerCreate.as_view(),
        name='player_create'),

    # Edit a Player, /steamapp/players/<steamid>/edit/
    url(r'^players/(?P<pk>\d+)/edit/$',
        LoginRequiredCheckIsOwnerUpdateView.as_view(
            model=Player,
            form_class=PlayerForm),
        name='player_edit'),

    # Delete a Player, /steamapp/players/<steamid>/delete/
    url(r'^players/(?P<pk>\d+)/delete/$',
        LoginRequiredCheckIsOwnerDeleteView.as_view(
           model=Player,
           success_url= reverse_lazy('steamapp:player_list')),
        name='player_delete'),

    # List Games: /steamapp/games.json
    url(r'^games(\.(?P<extension>(json|xml)))?$',
        GameList.as_view(),
        name='game_list'),

    # Game details, ex.: /steamapps/players/<appid>.json
    url(r'^games/(?P<pk>\d+)(\.(?P<extension>(json|xml)))?$',
        GameDetail.as_view(),
        name='game_detail'),

    # Create a Game: /steamapp/games/create/
    url(r'^games/create/$',
        GameCreate.as_view(),
        name='game_create'),

    # Edit a Game, /steamapp/games/<appid>/edit/
    url(r'^games/(?P<pk>\d+)/edit/$',
        LoginRequiredCheckIsOwnerUpdateView.as_view(
            model=Game,
            form_class=GameForm),
        name='game_edit'),

    # Create a GameReview, /steamapp/game/<ppid>/reviews/create/
    url(r'^steamapp/(?P<pk>\d+)/reviews/create/$',
        GameReviewCreate.as_view(),
        name='review_create'),


    # Delete a Game, /steamapp/games/<appid>/delete/
    url(r'^games/(?P<pk>\d+)/delete/$',
        LoginRequiredCheckIsOwnerDeleteView.as_view(
           model=Game,
           success_url= reverse_lazy('steamapp:game_list')),
        name='game_delete'),

    # Owned games details, ex.:  /steamapps/ownedgames/<id>.json
    url(r'^ownedgames/(?P<pk>\d+)(\.(?P<extension>(json|xml)))?$',
        OwnedGameDetail.as_view(),
        name='ownedgame_detail'),

    # Create a OwnedGame: /steamapp/ownedgames/player/create/<steamid>
    # From a Player
    url(r'^ownedgames/player/create/(?P<pk>\d+)$',
        OwnedGamePlayerCreate.as_view(),
        name='ownedgameplayer_create'),

    # Create a OwnedGame: /steamapp/ownedgames/game/create/<appid>
    # From a Game
    url(r'^ownedgames/game/create/(?P<pk>\d+)$',
        OwnedGameGameCreate.as_view(),
        name='ownedgamegame_create'),

    # Edit a OwnedGame, /steamapp/ownedgames/<id>/edit/
    url(r'^ownedgames/(?P<pk>\d+)/edit/$',
        LoginRequiredCheckIsOwnerUpdateView.as_view(
            model=OwnedGame,
            form_class=OwnedGameForm),
        name='ownedgame_edit'),

    # Delete a OwnedGame, /steamapp/ownedgames/<id>/delete/
    url(r'^ownedgames/(?P<pk>\d+)/delete/$',
        LoginRequiredCheckIsOwnerDeleteView.as_view(
           model=OwnedGame,
           success_url = reverse_lazy('steamapp:home')),
        name='ownedgame_delete'),

    # List Achievements: /steamapp/achievements.json
    url(r'^achievements(\.(?P<extension>(json|xml)))?$',
        AchievementList.as_view(),
        name='achievement_list'),

    # Achievements details, ex.: /steamapps/achievements/<id>.json
    url(r'^achievements/(?P<pk>\d+)(\.(?P<extension>(json|xml)))?$',
        AchievementDetail.as_view(),
        name='achievement_detail'),

    # Create a Achievement: /steamapp/achievements/create/
    url(r'^achievements/create/$',
        AchievementCreate.as_view(),
        name='achievement_create'),

    # Create a Achievement: /steamapp/achievements/game/create/<appid>
    # From a Game
    url(r'^achievements/game/create/(?P<pk>\d+)$',
        AchievementGameCreate.as_view(),
        name='achievementgame_create'),

    # Edit a Achievement, /steamapp/achievements/<id>/edit/
    url(r'^achievements/(?P<pk>\d+)/edit/$',
        LoginRequiredCheckIsOwnerUpdateView.as_view(
            model=Achievement,
            form_class=AchievementForm),
        name='achievement_edit'),

    # Delete a Achievement, /steamapp/achievements/<id>/delete/
    url(r'^achievements/(?P<pk>\d+)/delete/$',
        LoginRequiredCheckIsOwnerDeleteView.as_view(
           model=Achievement,
           success_url= reverse_lazy('steamapp:achievement_list')),
        name='achievement_delete'),

    # Owned Achievements details, ex.:  /steamapps/ownedachievements/<id>.json
    url(r'^ownedachievements/(?P<pk>\d+)(\.(?P<extension>(json|xml)))?$',
        OwnedAchievementDetail.as_view(),
        name='ownedachievement_detail'),

    # Create a OwnedAchievement: /steamapp/ownedachievements/player/create/<steamid>
    # From a Player
    url(r'^ownedachievements/player/create/(?P<pk>\d+)$',
        OwnAchPlayerCreate.as_view(),
        name='ownedachievementplayer_create'),

    # Create a OwnedAchievement: /steamapp/ownedachievements/achievement/create/<id>
    # From a Achievement
    url(r'^ownedachievements/achievement/create/(?P<pk>\d+)$',
        OwnAchAchCreate.as_view(),
        name='ownedachievementach_create'),

    # Edit a OwnedAchievement, /steamapp/ownedachievements/<id>/edit/
    url(r'^ownedachievements/(?P<pk>\d+)/edit/$',
        LoginRequiredCheckIsOwnerUpdateView.as_view(
            model=OwnedAchievement,
            form_class=OwnedAchievementForm),
        name='ownedachievement_edit'),

    # Delete a OwnedAchievement, /steamapp/ownedachievements/<id>/delete/
    url(r'^ownedachievements/(?P<pk>\d+)/delete/$',
        LoginRequiredCheckIsOwnerDeleteView.as_view(
           model=OwnedAchievement,
           success_url = reverse_lazy('steamapp:home')),
        name='ownedachievement_delete'),


    # API patterns
    url(r'^api/players/$',  APIPlayerList.as_view(),  name='player-list'),
    url(r'^api/players/(?P<pk>\d+)/$',
            APIPlayerDetail.as_view(), name='player-detail'),
    url(r'^api/games/$',  APIGameList.as_view(),  name='game-list'),
    url(r'^api/games/(?P<pk>\d+)/$',
            APIGameDetail.as_view(), name='game-detail'),
    url(r'^api/achievements/$',
            APIAchievementList.as_view(),  name='achievement-list'),
    url(r'^api/achievements/(?P<pk>\d+)/$',
            APIAchievementDetail.as_view(), name='achievement-detail'),
    url(r'^api/ownedgames/(?P<pk>\d+)/$',
            APIOwnedGameDetail.as_view(), name='ownedgame-detail'),
    url(r'^api/ownedachievements/(?P<pk>\d+)/$',
            APIOwnedAchievementDetail.as_view(), name='ownedachievement-detail'),
]

# Format suffixes
urlpatterns = format_suffix_patterns(urlpatterns, allowed=['api','json', 'xml'])

steamapp/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from datetime import date

class Player(models.Model):
    steamid = models.TextField(primary_key=True)
    nickname = models.TextField()
    profileurl = models.TextField()
    privacy = models.TextField(default="private")
    country = models.TextField(blank=True, null=True)
    lastlog = models.IntegerField(default=0)
    user = models.ForeignKey(User, default=1)

    def __unicode__(self):
        return self.nickname

    def get_absolute_url(self):
        return reverse('steamapp:player_detail', kwargs={'pk': self.pk})


class Game(models.Model):
    appid = models.TextField(primary_key=True)
    name = models.TextField()
    user = models.ForeignKey(User, default=1)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('steamapp:game_detail', kwargs={'pk': self.pk})

    def averageRating(self):
        ratingSum = sum([float(review.rating) for review in self.gamereview_set.all()])
        reviewCount = self.gamereview_set.count()
        return ratingSum / reviewCount

class Review(models.Model):
    RATING_CHOICES = ((1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five'))
    rating = models.PositiveSmallIntegerField('Rating (stars)', blank=True, default=3, choices=RATING_CHOICES)
    comment = models.TextField(blank=True, null=True)
    user = models.ForeignKey(User, default=1)
    date = models.DateField(default=date.today)

    class Meta:
        abstract = True

class GameReview(Review):
    game = models.ForeignKey(Game)

    def __unicode__(self):
        return self.game.name

    def get_absolute_url(self):
        return reverse('steamapp:game_detail', kwargs={'pk': self.game.appid})


class OwnedGame(models.Model):
    steamid = models.ForeignKey(Player, null = True, related_name='ownedgames')
    appid = models.ForeignKey(Game, null = True, related_name='gamesownedby')
    nickname = models.TextField(blank=True, null=True)
    gamename = models.TextField(blank=True, null=True)
    timeplayed_forever = models.IntegerField(default=0)
    user = models.ForeignKey(User, default=1)

    class Meta:
        unique_together = (('steamid', 'appid'),)

    def __unicode__(self):
        return "{ Player: " + self.nickname + ", Game: " + self.gamename + " }"

    def get_absolute_url(self):
        return reverse('steamapp:ownedgame_detail', kwargs={'pk': self.pk})


class Achievement(models.Model):
    apiname = models.TextField(blank=True, null=True)
    appid = models.ForeignKey(Game, related_name='achievements')
    gamename = models.TextField(blank=True, null=True)
    displayname = models.TextField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    user = models.ForeignKey(User, default=1)

    def __unicode__(self):
        return  self.displayname

    def get_absolute_url(self):
        return reverse('steamapp:achievement_detail', kwargs={'pk': self.pk})


class OwnedAchievement(models.Model):
    steamid = models.ForeignKey(Player, related_name='ownedachievements')
    achid = models.ForeignKey(Achievement, related_name='achievementsownedby')
    nickname = models.TextField(blank=True, null=True)
    achieved = models.TextField(default='No')
    user = models.ForeignKey(User, default=1)

    class Meta:
        unique_together = (('steamid', 'achid'),)

    def __unicode__(self):
        return "{ Player: " + self.nickname + " - " + self.achid.displayname \
               + " - State: " + self.achieved + " }"

    def get_absolute_url(self):
        return reverse('steamapp:ownedachievement_detail', kwargs={'pk': self.pk})

steamapp/forms.py
from django.forms import ModelForm
from models import Player, Game, Achievement, OwnedGame, OwnedAchievement, GameReview

class PlayerForm(ModelForm):
    class Meta:
        model = Player
        exclude = ('user',)

class GameForm(ModelForm):
    class Meta:
        model = Game
        exclude = ('user',)

class GameReviewForm(ModelForm):
    class Meta:
        model = GameReview
        exclude = ('user','date','game',)

class AchievementForm(ModelForm):
    class Meta:
        model = Achievement
        exclude = ('user',)

class AchievementGameForm(ModelForm):
    class Meta:
        model = Achievement
        exclude = ('user','appid','gamename',)

class OwnedGameForm(ModelForm):
    class Meta:
        model = OwnedGame
        exclude = ('user',)

class OwnedGamePlayerForm(ModelForm):
    class Meta:
        model = OwnedGame
        exclude = ('user','steamid','nickname',)

class OwnedGameGameForm(ModelForm):
    class Meta:
        model = OwnedGame
        exclude = ('user','appid','gamename',)

class OwnedAchievementForm(ModelForm):
    class Meta:
        model = OwnedAchievement
        exclude = ('user',)

class OwnedAchievementPlayerForm(ModelForm):
    class Meta:
        model = OwnedAchievement
        exclude = ('user','steamid','nickname')

class OwnedAchievementAchForm(ModelForm):
    class Meta:
        model = OwnedAchievement
        exclude = ('user','achid',)

steamapp/templates/steamapp/achievement_detail.html
{% extends "steamapp/base.html" %}
{% block content %}

<div id="sidebar">
  <h2 align="left">
    {% block sidebar %}<ul><li><a href="/steamapp">Home</a></li></ul>{% endblock %}
    <br/>
  </h2>
</div>

<h1> <a href="{% url 'steamapp:achievement_list' %}"> List of Achievements </a> > Achievement: </h1>
<h1>
    {{ achievement.displayname }}
    {% if user == achievement.user %}
        (<a href="{% url 'steamapp:achievement_edit' achievement.id %}">edit</a>)
    {% endif %}

    {% if user == achievement.user %}
        (<a href="{% url 'steamapp:achievement_delete' achievement.id %}">delete</a>)
    {% endif %}
</h1>

<h2>Apiname</h2>
<p>
    {{ achievement.apiname }}<br/>
</p>

<h2>Game</h2>
<p>
Appid: {{achievement.appid.appid}}
</p>
<p>
Name:
<a href="{% url 'steamapp:game_detail' achievement.appid.appid %}">{{ achievement.appid.name}}</a>
</p>

<h2>Description</h2>
<p>
    {{ achievement.description }}<br/>
</p>

<h2> Achievement registered for
    {% if user.is_authenticated %}
        (<a href="{% url 'steamapp:ownedachievementach_create' achievement.id %}">add</a>)
    {% endif %}
</h2>

{% for ownach in achievement.achievementsownedby.all %}
    <a href="{% url 'steamapp:ownedachievement_detail' ownach.id %}">
        {{ ownach.steamid.nickname }}</a><br/>
{% empty %}<p>This achievement is not registered in any player</p>
{% endfor %}


{% endblock %}

steamapp/templates/steamapp/achievement_list.html
{% extends "steamapp/base.html" %}
{% block content %}
<div id="sidebar">
  <h2 align="left">
    {% block sidebar %}<ul><li><a href="/steamapp">Home</a></li></ul>{% endblock %}
    <br/>
  </h2>
</div>

<h1>
  Achievements
  {% if user.is_authenticated %}(<a href="{% url 'steamapp:achievement_create' %}">add</a>){% endif %}
</h1>

    {% for achievement in achievement_list %}
        <a href="{% url 'steamapp:achievement_detail' achievement.id %}">
            {{ achievement.displayname }}</a><br/>
    {% empty %}<p>No achievements registered yet.</p>
    {% endfor %}

{% endblock %}

steamapp/templates/steamapp/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css" />
    <script src="http://code.jquery.com/jquery-2.2.3.js"></script>
    <script src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <title>{% block title %}Steamapp by CSL &amp; ACR{% endblock %}</title>
</head>

<body>

<div id="header">
  <h2 align="right">
    {% block header %}
        {% if user.is_authenticated %}
            <p>Welcome, {{ user.username }}  <a href="{% url 'steamapp:logout' %}?next={{request.path}}"> [Log out]</a></p>
        {% else %}
            <p>Welcome, Guest <a href="{% url 'steamapp:login' %}?next={{request.path}}"> [Log in]</a></p>

        {% endif %}
    {% endblock %}
  </h2>
</div>

<div id="content" align="center">
    {% block content %}
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% endblock %}
</div>

<div id="footer">{% block footer %}Powered by CSL &amp; ACR{% endblock %}</div>
</body>

</html>

steamapp/templates/steamapp/game_detail.html
{% extends "steamapp/base.html" %}
{% block title %}Steamapp - {{game.name }}{% endblock %}

{% block content %}

<div id="sidebar">
  <h2 align="left">
    {% block sidebar %}<ul><li><a href="/steamapp">Home</a></li></ul>{% endblock %}
    <br/>
  </h2>
</div>


<h1> <a href="{% url 'steamapp:game_list' %}"> List of Games </a> > Game: </h1>


<span vocab="http://schema.org/" typeof="VideoGame">
<h1>
    <span property="name">{{ game.name }}</span>
    <span property="applicationCategory" content="Steam"> </span>
    <span property="description" content="Steam video game"> </span>
    <span property="genre" content="No specified"> </span>
    <span rel="offers">
      <span typeof="Offer">
        <span property="name" content="Offer"> </span>
        <span property="price" content="0.00"> </span>
        <span property="priceCurrency" content="Euros"> </span>
      </span>
    </span>
    <span property="operatingSystem" content="For sure Windows, maybe also Linux and Mac"> </span>
    <span property="sameAs" content="http://store.steampowered.com/"> </span>
    <span property="url" content="http://store.steampowered.com/"> </span>

    {% if user == game.user %}
        (<a href="{% url 'steamapp:game_edit' game.appid %}">edit</a>)
    {% endif %}

    {% if user == game.user %}
        (<a href="{% url 'steamapp:game_delete' game.appid %}">delete</a>)
    {% endif %}

</h1>

<h2>Appid</h2>
    <p>
    {{ game.appid }}
    </p>


<h2>Reviews
    {% if user.is_authenticated %}
        (<a href="{% url 'steamapp:review_create' game.appid %}">add</a>)
    {% endif %}
</h2>

{% if game.gamereview_set.all|length > 0 %}
<span rel="aggregateRating">
    <span typeof="AggregateRating">
        Average rating <span property="ratingValue">{{ game.averageRating|stringformat:".1f" }} </span>
        {% with game.gamereview_set.all|length as reviewCount %}
        from <span property="reviewCount">{{ reviewCount }}</span> review{{ reviewCount|pluralize }}
        {% endwith %}

    </span>
</span>



<span rel="review">
    {% for review in game.gamereview_set.all %}
      <span typeof="Review">
            <p rel="reviewRating" typeof="Rating">
                <span property="worstRating" content="{{ RATING_CHOICES.0.0 }}"></span>
                <span property="ratingValue" content="1.5">{{ review.rating }}</span> star{{ review.rating|pluralize }}
                {% with RATING_CHOICES|last as best %}
                <span property="bestRating" content="{{ best.0 }}"></span>
                {% endwith %}
            </p>
            <p property="description">{{ review.comment }}</p>
            <p>Created by <span property="author">{{ review.user }}</span> on
                <span property="datePublished" content="{{ review.date|date:'Y-m-d' }}">{{ review.date }}</span></p>
        </span>
        <br/>
    {% endfor %}
  {% endif %}
</span>


<h2> Game Achievements
    {% if user.is_authenticated %}
        (<a href="{% url 'steamapp:achievementgame_create' game.appid %}">add</a>)
    {% endif %}
</h2>

{% for achievement in game.achievements.all %}
    <a href="{% url 'steamapp:achievement_detail' achievement.id %}">
        {{ achievement.displayname }}</a><br/>
{% empty %}<p>This game either does not have achievements or have but not registered</p>
{% endfor %}


<h2> Game Owned by
    {% if user.is_authenticated %}
        (<a href="{% url 'steamapp:ownedgamegame_create' game.appid %}">add</a>)
    {% endif %}
</h2>

{% for ownedgame in game.gamesownedby.all %}
    <a href="{% url 'steamapp:ownedgame_detail' ownedgame.id %}">
        {{ ownedgame.nickname }}</a><br/>
{% empty %}<p>This game is not owned for any user</p>
{% endfor %}

{% endblock %}

steamapp/templates/steamapp/game_list.html
{% extends "steamapp/base.html" %}
{% block content %}

<div id="sidebar">
  <h2 align="left">
    {% block sidebar %}<ul><li><a href="/steamapp">Home</a></li></ul>{% endblock %}
    <br/>
  </h2>
</div>

<h1>
    Games
    {% if user.is_authenticated %}(<a href="{% url 'steamapp:game_create' %}">add</a>){% endif %}
</h1>

    {% for game in game_list %}
        <a href="{% url 'steamapp:game_detail' game.appid %}">
            {{ game.name }}</a><br/>
    {% empty %}<p>No games registered yet.</p>
    {% endfor %}

{% endblock %}

steamapp/templates/steamapp/ownach_detail.html
{% extends "steamapp/base.html" %}
{% block content %}

<div id="sidebar">
  <h2 align="left">
    {% block sidebar %}<ul><li><a href="/steamapp">Home</a></li></ul>{% endblock %}
    <br/>
  </h2>
</div>

<h1>
    Achievement:
    <a href="{% url 'steamapp:achievement_detail' ownedachievement.achid.id %}"> {{ ownedachievement.achid.displayname }}</a>
    Owned by Player:
    <a href="{% url 'steamapp:player_detail' ownedachievement.steamid.steamid %}">{{ ownedachievement.nickname}}</a>

    {% if user == ownedachievement.user %}
        (<a href="{% url 'steamapp:ownedachievement_edit' ownedachievement.id %}">edit</a>)
    {% endif %}

    {% if user == ownedachievement.user %}
        (<a href="{% url 'steamapp:ownedachievement_delete' ownedachievement.id %}">delete</a>)
    {% endif %}
</h1>

<h2>Apiname</h2>
<p>
    {{ ownedachievement.achid.apiname }}<br/>
</p>

<h2>Player Info</h2>
<p>
Steam id: {{ownedachievement.steamid.steamid}}
</p>
<p>
Name: {{ ownedachievement.nickname}}</a>
</p>


<h2>Achieved</h2>
<p>
    {{ ownedachievement.achieved }}<br/>
</p>


{% endblock %}

steamapp/templates/steamapp/ownedgame_detail.html
{% extends "steamapp/base.html" %}
{% block content %}

<div id="sidebar">
  <h2 align="left">
    {% block sidebar %}<ul><li><a href="/steamapp">Home</a></li></ul>{% endblock %}
    <br/>
  </h2>
</div>

<h1>
    <a href="{% url 'steamapp:game_detail' ownedgame.appid.appid %}">{{ ownedgame.gamename}}</a>
    Owned by
    <a href="{% url 'steamapp:player_detail' ownedgame.steamid.steamid %}">{{ ownedgame.nickname }}</a>

    {% if user == ownedgame.user %}
        (<a href="{% url 'steamapp:ownedgame_edit' ownedgame.id %}">edit</a>)
    {% endif %}

    {% if user == ownedgame.user %}
        (<a href="{% url 'steamapp:ownedgame_delete' ownedgame.id %}">delete</a>)
    {% endif %}
</h1>

<h2>Steam id 64 bits</h2>
<p>
    {{ ownedgame.steamid.steamid }}<br/>
</p>

<h2>Appid</h2>
<p>
    {{ ownedgame.appid.appid }}<br/>
</p>

<h2>Time played in minutes</h2>
<p>
    {{ ownedgame.timeplayed_forever }}<br/>
</p>


{% endblock %}

steamapp/templates/steamapp/player_detail.html
{% extends "steamapp/base.html" %}
{%  block  title  %}Player - {{  player.nickname  }} {%  endblock  %}
{% block content %}

<div id="sidebar">
<h2 align="left">
    {% block sidebar %}
    <ul><li>
        <a href="/steamapp">Home </a> >
        <a href="{% url 'steamapp:player_list' %}"> List of Players </a> > Player:
    </li></ul>
    {% endblock %}
</h2>
</div>

<span vocab="http://schema.org/"  typeof="Person">

<h1>
    <span property="name"> {{ player.nickname }} </span>

    {% if user == player.user %}
        (<a href="{% url 'steamapp:player_edit' player.steamid %}">edit</a>)
    {% endif %}

    {% if user == player.user %}
        (<a href="{% url 'steamapp:player_delete' player.steamid %}">delete</a>)
    {% endif %}
    </span>
</h1>

<h2>
    <span title="steamid"> Steam ID 64 bits </span>
</h2>

<p>
    <span property="taxID"> {{ player.steamid }} </span>
</p>

<h2>
    <span title="profile-url"> Profile URL </span>
</h2>

<p>
    <span property="url"> {{ player.profileurl }} </span>
</p>

<h2>
    <span title="profile-privacy"> Privacy </span>
</h2>

<p>
    {{ player.privacy }}
</p>

<h2>
    <span title="country"> Country </span>
</h2>

<p>
    <span property="nationality"> {{ player.country }} </span>
</p>

<h2>
    <span title="last-log"> Last log (Unix Time) </span>
</h2>

<p>
    {{ player.lastlog }}
</p>

<h2> Player Games
    {% if user.is_authenticated %}(<a href="{% url 'steamapp:ownedgameplayer_create' player.steamid %}">add</a>){% endif %}
</h2>

  {% for ownedgame in player.ownedgames.all %}
      <a href="{% url 'steamapp:ownedgame_detail' ownedgame.id %}">
        {{ ownedgame.gamename }}</a><br/>
  {% empty %}<p>Either no games owned or private profile.</p>
  {% endfor %}


<h2> Player Achievements
    {% if user.is_authenticated %}(<a href="{% url 'steamapp:ownedachievementplayer_create' player.steamid  %}">add</a>){% endif %}
</h2>

  {% for ownach in player.ownedachievements.all %}
      <a href="{% url 'steamapp:ownedachievement_detail' ownach.id %}">
          {{ ownach.achid.displayname }}</a><br/>
  {% empty %}<p>This player has not achievements registered</p>
  {% endfor %}


{% endblock %}